/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.poo115.inmobiliaria.vistas;

import com.poo115.inmobiliaria.modelos.Propietario;
import com.poo115.inmobiliaria.persistencia.PropietarioDAO;
import java.util.List;
import java.util.regex.Pattern; 
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList; 


/**
 *
 * @author NixieNixi
 */
public class FrmGestionPropietarios extends javax.swing.JFrame {

    
    private PropietarioDAO propietarioDao;
    private DefaultTableModel tableModel;

    private static final String EMAIL_REGEX = "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6}$";
    private static final String TELEFONO_REGEX = "^[267]\\d{7}$";
    /**
     * Creates new form FrmGestionPropietarios
     */
    public FrmGestionPropietarios() 
    {
        initComponents();
        this.propietarioDao = new PropietarioDAO();

        configurarModeloTabla();

        cargarTabla();

        configurarListenerTabla();

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIdPropietario = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtIdPropietario = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPropietarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Propietarios");

        lblIdPropietario.setText("ID Propietario");

        lblNombre.setText("Nombre:");

        lblTelefono.setText("Telefono:");

        lblCorreo.setText("Correo:");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar Formulario");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        tblPropietarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPropietarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCorreo)
                    .addComponent(lblTelefono)
                    .addComponent(lblNombre)
                    .addComponent(lblIdPropietario))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdPropietario, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(txtNombre)
                    .addComponent(txtTelefono)
                    .addComponent(txtCorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(124, 124, 124))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiar)
                .addGap(95, 95, 95))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdPropietario)
                            .addComponent(txtIdPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnRegistrar)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEditar)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefono)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lblCorreo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnEliminar)))
                .addGap(13, 13, 13)
                .addComponent(btnLimpiar)
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (validarCampos(true)) {
            
            String id = txtIdPropietario.getText();
            
            if (propietarioDao.buscarPropietarioPorId(id) != null) {
                 JOptionPane.showMessageDialog(this, 
                         "El ID de Propietario ingresado ya existe. Intente con otro.", 
                         "Error: ID Duplicado", 
                         JOptionPane.WARNING_MESSAGE);
                 return; 
            }

            String nombre = txtNombre.getText();
            String telefono = txtTelefono.getText();
            String correo = txtCorreo.getText();
            List<String> propiedadesAsociadas = new ArrayList<>(); 

            Propietario p = new Propietario(id, nombre, telefono, correo, propiedadesAsociadas);
            
            propietarioDao.registrarPropietario(p);
            
            JOptionPane.showMessageDialog(this, 
                    "Propietario registrado con exito.", 
                    "Registro Exitoso", 
                    JOptionPane.INFORMATION_MESSAGE);
            cargarTabla();
            limpiarFormulario();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (txtIdPropietario.getText().isBlank() || txtIdPropietario.isEnabled()) {
             JOptionPane.showMessageDialog(this, 
                     "Por favor, seleccione un propietario de la tabla para editar.", 
                     "Error de Selecion", 
                     JOptionPane.WARNING_MESSAGE);
             return;
        }
        
        if (!validarCampos(false)) {
            return;
        }
        
        String id = txtIdPropietario.getText(); 
        String nombre = txtNombre.getText();
        String telefono = txtTelefono.getText();
        String correo = txtCorreo.getText();

        Propietario pExistente = propietarioDao.buscarPropietarioPorId(id);
        List<String> propiedadesAsociadas = (pExistente != null) ? pExistente.getPropiedadesAsociadas() : new ArrayList<>();

        Propietario p = new Propietario(id, nombre, telefono, correo, propiedadesAsociadas);
        
        boolean exito = propietarioDao.editarPropietario(p);
        
        if (exito) {
            JOptionPane.showMessageDialog(this, "Propietario actualizado con éxito.", "Actualización Exitosa", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo actualizar el propietario (ID no encontrado).", "Error", JOptionPane.ERROR_MESSAGE);
        }
        cargarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = tblPropietarios.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, 
                    "Seleccione un propietario de la tabla para eliminar.", 
                    "Error de Selección", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String id = tblPropietarios.getValueAt(filaSeleccionada, 0).toString();
      
        
        int confirmacion = JOptionPane.showConfirmDialog(this, 
            "¿Está seguro de que desea eliminar al propietario con ID: " + id + "?", 
            "Confirmar Eliminación", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

        if (confirmacion == JOptionPane.YES_OPTION) {
            boolean exito = propietarioDao.eliminarPropietario(id);
            
            if (exito) {
                JOptionPane.showMessageDialog(this, "Propietario eliminado con éxito.", "Eliminación Exitosa", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar el propietario.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            cargarTabla();
            limpiarFormulario();
        }    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGestionPropietarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGestionPropietarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGestionPropietarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGestionPropietarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGestionPropietarios().setVisible(true);
            }
        });
    }

    
    private void configurarModeloTabla()
    {
        tableModel = new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"ID Propietario", "Nombre", "Teléfono", "Correo"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblPropietarios.setModel(tableModel);
    } 
    
    
    private void cargarTabla()
    {
        tableModel.setRowCount(0);
        
        List<Propietario> propietarios = propietarioDao.obtenerTodosLosPropietarios();
        
        for (Propietario p : propietarios) {
            tableModel.addRow(new Object[]{
                p.getIdPropietario(),
                p.getNombre(),
                p.getTelefono(),
                p.getCorreo()
            });
        }
    }
    
    /**
     * Resetea todos los campos del formulario a sus valores por defecto.
     */
    private void limpiarFormulario() 
    {
        txtIdPropietario.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        
        txtIdPropietario.setEnabled(true);
    }
    
    /**
     * Valida que los campos del formulario no estén vacíos
     * y que el teléfono y correo tengan formatos válidos.
     * @param esRegistro Si es true, valida también el campo ID.
     * @return true si la validación es exitosa, false en caso contrario.
     */
    private boolean validarCampos(boolean esRegistro) {
        String id = txtIdPropietario.getText();
        String nombre = txtNombre.getText();
        String telefono = txtTelefono.getText();
        String correo = txtCorreo.getText();

        if (nombre.isBlank() || telefono.isBlank() || correo.isBlank()) {
            JOptionPane.showMessageDialog(this, 
                    "Los campos Nombre, Teléfono y Correo no pueden estar vacíos.", 
                    "Error de Validación", 
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        if (esRegistro && id.isBlank()) {
             JOptionPane.showMessageDialog(this, 
                    "El campo ID Propietario no puede estar vacío.", 
                    "Error de Validación", 
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        if (!Pattern.matches(TELEFONO_REGEX, telefono)) {
             JOptionPane.showMessageDialog(this, 
                    "Formato de teléfono inválido. Debe ser un número de 8 dígitos (Ej. 77778888).", 
                    "Error de Formato", 
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
         if (!Pattern.matches(EMAIL_REGEX, correo)) {
             JOptionPane.showMessageDialog(this, 
                    "Formato de correo electrónico inválido.", 
                    "Error de Formato", 
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        return true;
    }
    
   
    private void configurarListenerTabla() {
        tblPropietarios.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int filaSeleccionada = tblPropietarios.getSelectedRow();
                
                if (filaSeleccionada != -1) {
                    String id = tableModel.getValueAt(filaSeleccionada, 0).toString();
                    String nombre = tableModel.getValueAt(filaSeleccionada, 1).toString();
                    String telefono = tableModel.getValueAt(filaSeleccionada, 2).toString();
                    String correo = tableModel.getValueAt(filaSeleccionada, 3).toString();

                    txtIdPropietario.setText(id);
                    txtNombre.setText(nombre);
                    txtTelefono.setText(telefono);
                    txtCorreo.setText(correo);
                    
                    txtIdPropietario.setEnabled(false);
                }
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblIdPropietario;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTable tblPropietarios;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtIdPropietario;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
